#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@dns-forwarder[-1]
	add ucitrack dns-forwarder
	set ucitrack.@dns-forwarder[-1].init=dns-forwarder
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
